#! /usr/bin/env python

import twitter
from ConfigParser import ConfigParser
from optparse import OptionParser
from sys import argv
from os.path import expanduser
from termcolor import colored

def parseOptions(argv) :
    '''Does command line parsing of options.'''
    parser = OptionParser()

    parser.add_option('-u', '--update',
                      action = 'store_const',
                      const  = 'update',
                      dest   = 'action')

    parser.add_option('-t', '--test',
                      action = 'store_const',
                      const  = 'test',
                      dest   = 'action')

    parser.add_option('-l', '--list',
                      action = 'store',
                      dest   = 'list_arg')

    parser.add_option('-r', '--replies',
                      action = 'store_const',
                      const  = 'replies',
                      dest   = 'action')

    options, args = parser.parse_args(argv[1:])

    try :
        if options.list_arg :
            options.action = 'list'
    except NameError :
        pass

    return options, args

def initAPI() :
    parser = ConfigParser()
    parser.read('%s/.chirprc' % expanduser('~'))

    api = twitter.Api(parser.get('authentication', 'username'),
                      parser.get('authentication', 'password'))

    return api

def main() :
    options, args = parseOptions(argv)

    api = initAPI()

    if options.action == 'update' :
        if args :
            status = args[0]
        else :
            status = []
            while True :
                try :
                    status.append(raw_input())
                except EOFError :
                    break

            status = '\n'.join(status)

        if len(status) > 140 :
            print "Message is too long, must be less than 140 characters."
            print "Current message is %d characters long." % len(status)
        else :
            api.PostUpdate(status)
            print "Posted update."
    elif options.action == 'list' :
        timeline = api.GetUserTimeline(user = options.list_arg)
        for status in timeline :
            print "-", status.GetText()
            print "\t- ", status.GetRelativeCreatedAt()

    elif options.action == 'list' :
        timeline = api.GetUserTimeline(user = options.list_arg)
        for status in timeline :
            print colored(status.user.screen_name, 'blue'), "-", colored(status.GetText(), 'yellow')
            print "\t- ", status.GetRelativeCreatedAt()

    elif options.action == 'replies':
        replies = api.GetReplies()
        for status in replies:
            print status.user.screen_name, "-", status.GetText()
            print "\t- ", status.GetRelativeCreatedAt()

    elif options.action == 'test' :
        print args

    return

if __name__ == '__main__' :
    main()

